project_name: iptv-proxy

builds:
  - binary: iptv-proxy
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
      - -a
    ldflags:
      - -s -w
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: WireshJ
    name: iptv-proxy
  draft: false

nfpms:
  - vendor: WireshJ
    homepage: https://github.com/WireshJ/iptv-proxy
    maintainer: WireshJ
    description: Self-hosted reverse proxy for IPTV M3U playlists and Xtream Codes API
    license: GPL-3.0
    formats:
      - deb
      - rpm

dockers:
  - image_templates:
      - "ghcr.io/wireshj/iptv-proxy:{{ .Tag }}-arm64"
      - "ghcr.io/wireshj/iptv-proxy:v{{ .Major }}-arm64"
      - "ghcr.io/wireshj/iptv-proxy:v{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/wireshj/iptv-proxy:latest-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    ids:
      - iptv-proxy
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    skip_push: false

  - image_templates:
      - "ghcr.io/wireshj/iptv-proxy:{{ .Tag }}-amd64"
      - "ghcr.io/wireshj/iptv-proxy:v{{ .Major }}-amd64"
      - "ghcr.io/wireshj/iptv-proxy:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/wireshj/iptv-proxy:latest-amd64"
      - "ghcr.io/wireshj/iptv-proxy:{{ .Tag }}"
      - "ghcr.io/wireshj/iptv-proxy:v{{ .Major }}"
      - "ghcr.io/wireshj/iptv-proxy:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/wireshj/iptv-proxy:latest"
    use: buildx
    goos: linux
    goarch: amd64
    ids:
      - iptv-proxy
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    skip_push: false
